stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/dev_elixir/Dockerfile
      buildContext: .
      tag: krini/cwlab:oidc-${CICD_EXECUTION_SEQUENCE}
  when:
    branch:
      include:
      - development
      - master
      - feature/testing
- name: deploy-dev
  steps:
  - applyYamlConfig:
      path: ./kube/develop-deployment.yaml
  when:
    branch:
      include:
      - development
- name: deploy-master
  steps:
  - applyYamlConfig:
      path: ./kube/stable-deployment.yaml
  when:
    branch:
      include:
      - master
- name: deploy-feature-testing
  steps:
  - applyYamlConfig:
      path: ./kube/testing-deployment.yaml
  when:
    branch:
      include:
      - feature/testing
timeout: 60
notification: {}
