WEB_SERVER_HOST: localhost

WEB_SERVER_PORT: 5000

DEBUG: False

EXEC_PROFILES:
  cwltool_windows:
    
    shell: powershell

    exec: |
      . ${PYTHON_PATH} -m cwltool --default-container ubuntu:16.04 --outdir "${OUTPUT_DIR}" "${CWL}" "${RUN_YAML}" > "${LOG_FILE}" 2>&1
