WEB_SERVER_HOST: localhost 
WEB_SERVER_PORT: 5000
ENABLE_USERS: True
DEBUG: True  

EXEC_PROFILES:
    WES: 
        type: python
        max_retries: 2
        py_module: ./cwl2wes.py
        py_class: WES