WEB_SERVER_HOST: 0.0.0.0
WEB_SERVER_PORT: 5000 

TEMP_DIR: '/cwlab/tmp'
WORKFLOW_DIR: '/cwlab/worlflows'
EXEC_DIR: '/cwlab/exec'
INPUT_DIR: '/cwlab/input'
DB_DIR: '/cwlab/database'

DEBUG: False

EXEC_PROFILES:

  cwltool_singularity: 
    shell: bash
    max_retries: 0
    max_paralle_exec: 8

    timeout:
      pre_exec: 120
      exec: 2592000
      post_exec: 600

    exec: |
      "${PYTHON_PATH}" -m cwltool --debug --no-container --outdir "${OUTPUT_DIR}" "${WORKFLOW}" "${RUN_INPUT}" >> "${LOG_FILE}" 2>&1
