WEB_SERVER_HOST: 0.0.0.0
WEB_SERVER_PORT: 5000 

TEMP_DIR: '/cwlab/tmp'
WORKFLOW_DIR: '/cwlab/worlflows'
EXEC_DIR: '/cwlab/exec'
INPUT_DIR: '/cwlab/input'
DB_DIR: '/cwlab/database'

DEBUG: False

ENABLE_USERS: True
USE_OIDC: True
OIDC_CONF: {
  response_type: 'id_token token',
  scope: 'openid profile',
  authority: 'https://keycloak.infra.ingress.rancher.computational.bio/auth/realms/cwlab',
  client_id: 'cwlab1',
  redirect_uri: 'http://localhost:5000/loginoidc',
  post_logout_redirect_uri: 'http://localhost:5000',
  metadata: {
      issuer: 'https://keycloak.infra.ingress.rancher.computational.bio/auth/realms/cwlab',
      authorization_endpoint: 'https://keycloak.infra.ingress.rancher.computational.bio/auth/realms/cwlab/protocol/openid-connect/auth',
      userinfo_endpoint: 'https://keycloak.infra.ingress.rancher.computational.bio/auth/realms/cwlab/protocol/openid-connect/userinfo',
      end_session_endpoint: 'https://keycloak.infra.ingress.rancher.computational.bio/auth/realms/cwlab/protocol/openid-connect/logout',
      jwks_uri: 'https://keycloak.infra.ingress.rancher.computational.bio/auth/realms/cwlab/protocol/openid-connect/certs',
  },
  signingKeys: { "keys": [{ "kid": "vV7ZUJcgLS8a0p9rFXCqSsJ3DopI2LwOs2HUZvXjhS4", "kty": "RSA", "alg": "RS256", "use": "sig", "n": "iwpSicGDOCarEDTWOBEVsbAbZE_VWomYGNnWAncnjMnjZU33R9bnQji2ChhiLTGw0NgdUGhZLmp3hzew-mfKJLQ6l7D0_XM5vOiSLtl4Rdxv4XcPDx-ed4Kj3SBvDPmJwkdTairbQ3qEn1QVJynlGa51XPrtA9DIGsTZaXQP47_ChjdmHEldC6OcIWluDw5fqkZSiI_VR9bJFtsoS-UP6-Kt9OgyQVfqbdjJspAb_4Vpc17EJ4u6vIDsvmACOgixqFXU4DTYTnZRr0_nVbO7rSsk3Dn47sZlB8V35U2jaqv5R9_67g61VytoWxYHUeeNEKo1pnP3VzWULe2Y7TQ9ew", "e": "AQAB", "x5c": ["MIICmTCCAYECBgFveyimJjANBgkqhkiG9w0BAQsFADAQMQ4wDAYDVQQDDAVjd2xhYjAeFw0yMDAxMDYxMzU5MTlaFw0zMDAxMDYxNDAwNTlaMBAxDjAMBgNVBAMMBWN3bGFiMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiwpSicGDOCarEDTWOBEVsbAbZE/VWomYGNnWAncnjMnjZU33R9bnQji2ChhiLTGw0NgdUGhZLmp3hzew+mfKJLQ6l7D0/XM5vOiSLtl4Rdxv4XcPDx+ed4Kj3SBvDPmJwkdTairbQ3qEn1QVJynlGa51XPrtA9DIGsTZaXQP47/ChjdmHEldC6OcIWluDw5fqkZSiI/VR9bJFtsoS+UP6+Kt9OgyQVfqbdjJspAb/4Vpc17EJ4u6vIDsvmACOgixqFXU4DTYTnZRr0/nVbO7rSsk3Dn47sZlB8V35U2jaqv5R9/67g61VytoWxYHUeeNEKo1pnP3VzWULe2Y7TQ9ewIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQAsBdl7LHedl3HsHWaSUQwteZfwDx0IHFJ+qzooBzLV90GcEyXuJOmtQQ4hlagJw8EHkoxQcE353zkzI46iN+4iNTSccDSGwjGK6XC6M+uz13vvFhL5UJJA5iSWODdISFbkQA8cxBStOX5kTL8ljOpK0dIgXbty4AUonJgLTe72rxJY+gaFd6aCvNnG69Js56lP0RAdcIZNpBpMuZOl36kiN4fU9IaSTAgsXgMvTaPBVhkRgn3VMxxEmWz00gP9RKE7RYTjFnpZ688WAoZgYZCnKegITBb6mdJ6ueWS8+S4tf76jcV/zIrjN9HXVtLAMJgIk5GMe6if9Nz8cnRa7dJt"], "x5t": "7N-pF1QQGSr31uz8LS1fWKFzDww", "x5t#S256": "7q9ukcB9aMa1Y4zIPTrhMDahKgSZ1CPYfroZ8qt15Eg" }] }
}


EXEC_PROFILES:

  cwltool_singularity: 
    shell: bash
    max_retries: 0
    max_paralle_exec: 8

    timeout:
      pre_exec: 120
      exec: 2592000
      post_exec: 600

    exec: |
      "${PYTHON_PATH}" -m cwltool --debug --no-container --outdir "${OUTPUT_DIR}" "${WORKFLOW}" "${RUN_INPUT}" >> "${LOG_FILE}" 2>&1

  WES: 
    type: python
    max_retries: 2
    py_module: ./wes_exec_profile.py
    py_class: WES