# WEB_SERVER_HOST: localhost # If it shall only be available on the local machine, use "localhost".
                        # If it shall be remotely accessible from other machines on the same network, use "0.0.0.0".

WEB_SERVER_HOST: localhost

## (2) choose the port:
WEB_SERVER_PORT: 5000 # The default is 5000, if this port is blocked choose a different one

TEMP_DIR: 'C:\Users\kerst\OneDrive\home_dell\CWLab\scratch\temp'
CWL_DIR: 'C:\Users\kerst\OneDrive\home_dell\CWLab\scratch\CWL'
EXEC_DIR: 'C:\Users\kerst\OneDrive\home_dell\CWLab\scratch\exec'
INPUT_DIR: 'C:\Users\kerst\OneDrive\home_dell\CWLab\scratch\test_files\test_data'
DB_DIR: 'C:\Users\kerst\OneDrive\home_dell\CWLab\scratch\database'

DEBUG: True

ENABLE_USER_LOGIN: True

EXEC_PROFILES:
  cwltool_windows:
    
    shell: powershell

    max_retries: 0

    max_parallel_runs: 3

    wait_when_queued: 1

    exec: |
      . "${PYTHON_PATH}" -m cwltool --default-container ubuntu:16.04 --outdir "${OUTPUT_DIR}" "${CWL}" "${RUN_YAML}" 2>&1 | %{ "$_" } | Out-File -Encoding "UTF8" "${LOG_FILE}"
      "PID:" >> "${LOG_FILE}"
      $pid >> "${LOG_FILE}"

    eval: |
      $LAST_LINES = (Get-Content -Tail 2 "${LOG_FILE}")

      if ($LAST_LINES.Contains("Final process status is success")){$SUCCESS="True"} 
      else {$SUCCESS="False"; $ERR_MESSAGE = "cwltool failed - ${LAST_LINE}"}

