# WEB_SERVER_HOST: localhost # If it shall only be available on the local machine, use "localhost".
                        # If it shall be remotely accessible from other machines on the same network, use "0.0.0.0".

WEB_SERVER_HOST: 0.0.0.0

## (2) choose the port:
WEB_SERVER_PORT: 5000 # The default is 5000, if this port is blocked choose a different one

TEMP_DIR: '/mnt/c/Users/kerst/OneDrive/home_dell/CWLab/scratch/temp'
WORKFLOW_DIR: '/mnt/c/Users/kerst/OneDrive/home_dell/CWLab/scratch/wf_dir'
EXEC_DIR: '/mnt/c/Users/kerst/OneDrive/home_dell/CWLab/scratch/exec'
INPUT_DIR: '/mnt/c/Users/kerst/OneDrive/home_dell/CWLab/scratch/input'
DB_DIR: '/mnt/c/Users/kerst/OneDrive/home_dell/CWLab/scratch/database'

DEBUG: True

ENABLE_USERS: True
USE_OIDC: True
OIDC_CONF: {
  response_type: 'code token id_token',
  scope: 'openid profile email',
  authority: 'https://login.elixir-czech.org/oidc/',
  client_id: 'b1f68121-faec-4196-ab51-66eb61660ece',
  redirect_uri: 'https://cwlab-oidc.krini.ingress.rancher.computational.bio/loginoidc',
  post_logout_redirect_uri: 'https://cwlab-oidc.krini.ingress.rancher.computational.bio/',
  metadata: {
      issuer: 'https://login.elixir-czech.org/oidc/',
      authorization_endpoint: 'https://login.elixir-czech.org/oidc/authorize',
      userinfo_endpoint: 'https://login.elixir-czech.org/oidc/userinfo',
      end_session_endpoint: 'https://login.elixir-czech.org/oidc/endsession',
      jwks_uri: 'https://login.elixir-czech.org/oidc/jwk',
  },
}

EXEC_PROFILES:
  cwltool_local_test: # name of the exec profile
    
    # Choose the shell to use:
    #   bash (Linux/MacOs), cmd (Windows)
    shell: bash

    # how many times execution should be retried (default 3):
    max_retries: 3
    
    # timeout for each step in seconds 
    # if not specified the defaults are used:
    #   120 (pre_exec, eval, post_eval) and 86400 = 14h (exec),
    # to disable timeout set Null
    timeout:
      pre_exec: 120
      exec: 86400
      eval: 120
      post_exec: 120

    # available variables are:
    #   - JOB_ID
    #   - RUN_ID (please note: is only unique within a job)
    #   - CWL
    #   - RUN_INPUT
    #   - OUTPUT_DIR
    #   - LOG_FILE
    pre_exec: |
      touch "${OUTPUT_DIR}/pre_exec"
    exec: |
      cwltool --outdir "${OUTPUT_DIR}" "${WORKFLOW}" "${RUN_INPUT}" >> "${LOG_FILE}" 2>&1
    eval: | 
      LAST_LINE=$(tail -n 1 ${LOG_FILE})
      if [[ "${LAST_LINE}" == *"Final process status is success"* ]]
      then
        SUCCESS=True
      else
        SUCCESS=False
        ERR_MESSAGE="cwltool failed - ${LAST_LINE}"
      fi
    # Please note:
    # A SUCCESS vaiable has to be filled with true/false
    # If SUCCESS==false: the ERR_MESSAGE can provide further information 
    # such as error messages
    post_exec: |
      touch "${OUTPUT_DIR}/post_exec"

  cwltool_local_no_docker_test: # name of the exec profile
    
    # Choose the shell to use:
    #   bash (Linux/MacOs), cmd (Windows)
    shell: bash

    # how many times execution should be retried (default 3):
    max_retries: 3
    
    # timeout for each step in seconds 
    # if not specified the defaults are used:
    #   120 (pre_exec, eval, post_eval) and 86400 = 14h (exec),
    # to disable timeout set Null
    timeout:
      pre_exec: 120
      exec: 86400
      eval: 120
      post_exec: 120

    # available variables are:
    #   - JOB_ID
    #   - RUN_ID (please note: is only unique within a job)
    #   - CWL
    #   - RUN_INPUT
    #   - OUTPUT_DIR
    #   - LOG_FILE
    pre_exec: |
      touch "${OUTPUT_DIR}/pre_exec"
    exec: |
      cwltool --debug --no-container --outdir "${OUTPUT_DIR}" "${WORKFLOW}" "${RUN_INPUT}" >> "${LOG_FILE}" 2>&1
    eval: | 
      LAST_LINE=$(tail -n 1 ${LOG_FILE})
      if [[ "${LAST_LINE}" == *"Final process status is success"* ]]
      then
        SUCCESS=True
      else
        SUCCESS=False
        ERR_MESSAGE="cwltool failed - ${LAST_LINE}"
      fi
    # Please note:
    # A SUCCESS vaiable has to be filled with true/false
    # If SUCCESS==false: the ERR_MESSAGE can provide further information 
    # such as error messages
    post_exec: |
      touch "${OUTPUT_DIR}/post_exec"

  cwltool_local_singularity_test: # name of the exec profile
    
    # Choose the shell to use:
    #   bash (Linux/MacOs), cmd (Windows)
    shell: bash

    # how many times execution should be retried (default 3):
    max_retries: 3
    
    # timeout for each step in seconds 
    # if not specified the defaults are used:
    #   120 (pre_exec, eval, post_eval) and 86400 = 14h (exec),
    # to disable timeout set Null
    timeout:
      pre_exec: 120
      exec: 86400
      eval: 120
      post_exec: 120

    # available variables are:
    #   - JOB_ID
    #   - RUN_ID (please note: is only unique within a job)
    #   - CWL
    #   - RUN_INPUT
    #   - OUTPUT_DIR
    #   - LOG_FILE
    pre_exec: |
      touch "${OUTPUT_DIR}/pre_exec"
    exec: |
      cwltool --singularity --outdir "${OUTPUT_DIR}" "${WORKFLOW}" "${RUN_INPUT}" >> "${LOG_FILE}" 2>&1
    eval: | 
      LAST_LINE=$(tail -n 1 ${LOG_FILE})
      if [[ "${LAST_LINE}" == *"Final process status is success"* ]]
      then
        SUCCESS=True
      else
        SUCCESS=False
        ERR_MESSAGE="cwltool failed - ${LAST_LINE}"
      fi
    # Please note:
    # A SUCCESS vaiable has to be filled with true/false
    # If SUCCESS==false: the ERR_MESSAGE can provide further information 
    # such as error messages
    post_exec: |
      touch "${OUTPUT_DIR}/post_exec"


  test:
    shell: bash
    timeout:
      pre_exec: 120
      exec: 86400
      eval: 120
      post_exec: 120
    pre_exec: |
      touch "${OUTPUT_DIR}/pre_exec_test"
    exec: |
      touch "${OUTPUT_DIR}/exec_test"
    eval: | 
      touch "${OUTPUT_DIR}/eval"
    post_exec: |
      touch "${OUTPUT_DIR}/post_execs"
  cwltool_local: # name of the exec profile
    # Choose the shell to use:
    #   bash (Linux/MacOs), cmd (Windows)
    shell: bash
    
    # timeout for each step in seconds 
    # if not specified the defaults are used:
    #   120 (pre_exec, eval, post_eval) and 86400 = 14h (exec),
    # to disable timeout set Null
    timeout:
      pre_exec: 120
      exec: 86400
      eval: 120
      post_exec: 120

    # available variables are:
    #   - JOB_ID
    #   - RUN_ID (please note: is only unique within a job)
    #   - CWL
    #   - RUN_INPUT
    #   - OUTPUT_DIR
    #   - LOG_FILE
    exec: |
      cwltool --outdir "${OUTPUT_DIR}" "${WORKFLOW}" "${RUN_INPUT}" >> "${LOG_FILE}" 2>&1
    eval: | 
      LAST_LINE=$(tail -n 1 ${LOG_FILE})
      if [[ "${LAST_LINE}" == *"Final process status is success"* ]]
      then
        SUCCESS=True
      else
        SUCCESS=False
        ERR_MESSAGE="cwltool failed - ${LAST_LINE}"
      fi
    # Please note:
    # A SUCCESS vaiable has to be filled with true/false
    # If SUCCESS==false: the ERR_MESSAGE can provide further information 
    # such as error messages