# WEB_SERVER_HOST: localhost # If it shall only be available on the local machine, use "localhost".
                        # If it shall be remotely accessible from other machines on the same network, use "0.0.0.0".

WEB_SERVER_HOST: localhost

## (2) choose the port:
WEB_SERVER_PORT: 5000 # The default is 5000, if this port is blocked choose a different one

TEMP_DIR: 'C:\Users\kerst\OneDrive\home\CWLab\scratch\temp'
CWL_DIR: 'C:\Users\kerst\OneDrive\home\CWLab\scratch\CWL'
EXEC_DIR: 'C:\Users\kerst\OneDrive\home\CWLab\scratch\exec'
INPUT_DIR: 'C:\Users\kerst\OneDrive\home\CWLab\scratch\input'
DB_DIR: 'C:\Users\kerst\OneDrive\home\CWLab\scratch\database'

DEBUG: True

EXEC_PROFILES:
  cwltool_windows:
    
    shell: powershell

    max_retries: 0

    exec: |
      . ${PYTHON_PATH} -m cwltool --default-container ubuntu:16.04 --outdir "${OUTPUT_DIR}" "${CWL}" "${RUN_YAML}" > "${LOG_FILE}" 2>&1
