SECRET_KEY: 'you-will-never-guess'

TEMP_DIR: '/mnt/c/Users/kerst/OneDrive/home/CWLab/scratch/temp'
CWL_DIR: '/mnt/c/Users/kerst/OneDrive/home/CWLab/scratch/CWL'
EXEC_DIR: '/mnt/c/Users/kerst/OneDrive/home/CWLab/scratch/exec'
INPUT_DIR: '/mnt/c/Users/kerst/OneDrive/home/CWLab/scratch/input'
DB_DIR: '/mnt/c/Users/kerst/OneDrive/home/CWLab/scratch/database'

EXEC_PROFILES:
  cwltool_local:
    # available variables are:
    #   - CWL
    #   - RUN_YAML
    #   - OUTPUT_DIR
    #   - LOG_FILE
    pre_exec: |
      touch "${OUTPUT_DIR}/test"
    exec: |
      cwltool --outdir "${OUTPUT_DIR}" "${CWL}" "${RUN_YAML}" >> "${LOG_FILE}" 2&>1
    # SUCCESS vaiable has to be filled with true/false
    # If SUCCESS==false: INFO can provide further information 
    # such as error messages
    eval: | 
      LAST_LINE=$(tail -n 1 ${LOG_FILE})
      if [[ "${LAST_LINE}" == *"Final process status is success"* ]]
      then
        SUCCESS=true
      else
        SUCCESS=false
        INFO="cwltool failed - ${LAST_LINE}"
      fi
    post_exec: |
      touch "${OUTPUT_DIR}/test2"